# vim ft=yaml
# travis-ci.org definition for MDP build (based on PyMVPA configuration
# which in turn was based on nipype and nipy)
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them
#
# Alternative setups could have been done using anaconda etc, but I would
# prefer to test against what is in neurodebian
language: erlang
cache:
  - apt
before_install:
    # The ultimate one-liner setup for NeuroDebian repository
    - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
    # - sudo apt-get install $PYTHON-dev
    - travis_retry sudo apt-get install python-numpy python-joblib python-sklearn
install:
    - python setup.py build_ext --inplace
    - pip install --user -v coveralls codecov pytest-cov
script:
    - coverage run setup.py test # TODO: add args to limit coverage to mdp only
after_success:
    - coveralls
    - codecov
